export const initialNewUserState = {
  isQuestion: false,
  id: 0,
  accountFilled: false,
  userName: '',
  password: '',
  repeatPassword: '',
  userSRCAvatarIMG: '',

  profileFilled: false,
  firstName: '',
  lastName: '',
  birthDate: '',
  email: '',
  address: '',
  gender: '',

  contactsFilled: false,
  company: '',
  githubLink: '',
  facebookLink: '',
  selectLanguage: '',
  fax: '',
  phoneArray: [''],
  phoneN1: '',
  phoneN2: '',
  phoneN3: '',

  selectSkills: '',
  textareaField: '',
  checkboxArt: '',
  checkboxSport: '',
  checkboxJustWant: '',
  checkboxFemale: '',
  checkboxGuitar: '',
  checkboxWtf: '',

  error: undefined,
}
