export const newUser = {
  isQuestion: false,
  id: 0,
  keyDB: 1,
  userName: '',
  password: '',
  repeatPassword: '',
  userSRCAvatarIMG: '',
  firstName: '',
  lastName: '',
  birthDate: '',
  email: '',
  address: '',
  gender: '',

  company: '',
  githubLink: '',
  facebookLink: '',
  selectLanguage: '',
  fax: '',
  phoneArray: [''],
  phoneN1: '',
  phoneN2: '',
  phoneN3: '',

  selectSkills: '',
  textareaField: '',
  checkboxArt: '',
  checkboxSport: '',
  checkboxJustWant: '',
  checkboxFemale: '',
  checkboxGuitar: '',
  checkboxWtf: '',
}
