export let newUser = {
  id: 0,
  isQuestion: true,
  userName: '',
  password: '',
  repeatPassword: '',
  userSRCAvatarIMG: '',
  firstName: '',
  lastName: '',
  birthDate: null,
  email: '',
  address: '',
  gender: '',

  company: '',
  githubLink: '',
  facebookLink: '',
  selectLanguage: null,
  fax: '',
  phoneN1: '',
  phoneN2: '',
  phoneN3: '',
  quantityPhoneField: 2,

  selectSkills: '',
  textareaField: false,
  checkboxArt: false,
  checkboxSport: false,
  checkboxJustWant: false,
  checkboxFemale: false,
  checkboxGuitar: false,
  checkboxWtf: false,
}