import AvatarIMG1 from '../img/Ellipse(1).png'
import AvatarIMG2 from '../img/Ellipse(2).png'
import AvatarIMG3 from '../img/Ellipse(3).png'
import AvatarIMG4 from '../img/Ellipse(4).png'
import AvatarIMG5 from '../img/Ellipse(5).png'
import AvatarIMG6 from '../img/Ellipse(6).png'
import AvatarIMG7 from '../img/Ellipse(7).png'


export const users = [
  {
    id: 1,
    userName: 'Maxim 1',
    password: '2222',
    repeatPassword: '2222',
    userSRCAvatarIMG: [AvatarIMG1],
    firstName: 'Maxim',
    lastName: 'Morozov 1',
    fullName: 'Maxim Morozov 1',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email1@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: 'Sport,fitness, aerobica and staff like that',
    checkboxJustWant: 'just want to play games, I’m not living in this life',
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxWtf: 'WTF is “hobbies”???',
    lastUpdate: new Date(),
  },
  {
    id: 2,
    userName: 'Maxim 2',
    password: '2222',
    repeatPassword: '2222',
    userSRCAvatarIMG: [AvatarIMG2],
    firstName: 'Maxim',
    lastName: 'Morozov 2',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email2@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
    lastUpdate: new Date(2019, 5, 16, 1),
  },
  {
    id: 3,
    userName: 'Maxim 3',
    password: '111',
    repeatPassword: '111',
    userSRCAvatarIMG: [AvatarIMG3],
    firstName: 'Maxim',
    lastName: 'Morozov 3',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email3@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
    lastUpdate: new Date(2019, 5, 15, 1),
  },
  {
    id: 4,
    userName: 'Maxim 4',
    password: '111',
    repeatPassword: '111',
    userSRCAvatarIMG: [AvatarIMG4],
    firstName: 'Maxim',
    lastName: 'Morozov 4',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email4@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
    lastUpdate: new Date(2019, 5, 14, 1),
  },
  {
    id: 5,
    userName: 'Maxim 5',
    password: '111',
    repeatPassword: '111',
    userSRCAvatarIMG: [AvatarIMG5],
    firstName: 'Maxim',
    lastName: 'Morozov 5',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email5@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
    lastUpdate: new Date(2019, 5, 13, 1),
  },
  {
    id: 6,
    userName: 'Maxim 6',
    password: '111',
    repeatPassword: '111',
    userSRCAvatarIMG: [AvatarIMG6],
    firstName: 'Maxim',
    lastName: 'Morozov 6',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email6@gmail.com',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
    lastUpdate: new Date(2019, 5, 10, 1),
  },
  {
    id: 7,
    userName: 'Maxim 7',
    password: '111',
    repeatPassword: '111',
    userSRCAvatarIMG: [AvatarIMG7],
    firstName: 'Maxim',
    lastName: 'Morozov 7',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email7@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
    lastUpdate: new Date(2019, 5, 2, 1),
  },
  {
    id: 8,
    userName: 'Maxim 8',
    password: '111',
    repeatPassword: '111',
    userSRCAvatarIMG: [AvatarIMG7],
    firstName: 'Maxim',
    lastName: 'Morozov 8',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email8@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
    lastUpdate: new Date(2019, 5, 1, 1),
  },
  {
    id: 9,
    userName: 'Maxim 9',
    password: '2222',
    repeatPassword: '2222',
    userSRCAvatarIMG: [AvatarIMG1],
    firstName: 'Maxim',
    lastName: 'Morozov 9',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email9@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: 'Sport,fitness, aerobica and staff like that',
    checkboxJustWant: 'just want to play games, I’m not living in this life',
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxWtf: 'WTF is “hobbies”???',
    lastUpdate: new Date(2019, 4, 2, 1),
  },
  {
    id: 10,
    userName: 'Maxim 10',
    password: '2222',
    repeatPassword: '2222',
    userSRCAvatarIMG: [AvatarIMG2],
    firstName: 'Maxim',
    lastName: 'Morozov 10',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email10@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
    lastUpdate: new Date(2019, 4, 22, 1),
  },
  {
    id: 11,
    userName: 'Maxim 11',
    password: '111',
    repeatPassword: '111',
    userSRCAvatarIMG: [AvatarIMG3],
    firstName: 'Maxim',
    lastName: 'Morozov 11',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email11@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
    lastUpdate: new Date(2019, 5, 10, 1),
  },
  {
    id: 12,
    userName: 'Maxim 12',
    password: '111',
    repeatPassword: '111',
    userSRCAvatarIMG: [AvatarIMG4],
    firstName: 'Maxim',
    lastName: 'Morozov 12',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email12@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
    lastUpdate: new Date(2019, 3, 10, 1),
  },
  {
    id: 13,
    userName: 'Maxim 13',
    password: '111',
    repeatPassword: '111',
    userSRCAvatarIMG: [AvatarIMG5],
    firstName: 'Maxim',
    lastName: 'Morozov 13',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email13@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
    lastUpdate: new Date(2010, 3, 10, 1),
  },
  {
    id: 14,
    userName: 'Maxim 14',
    password: '111',
    repeatPassword: '111',
    userSRCAvatarIMG: [AvatarIMG6],
    firstName: 'Maxim',
    lastName: 'Morozov 14',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email14@gmail.com',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
    lastUpdate: new Date(2000, 3, 10, 1),
  },
  {
    id: 15,
    userName: 'Maxim 15',
    password: '111',
    repeatPassword: '111',
    userSRCAvatarIMG: [AvatarIMG7],
    firstName: 'Maxim',
    lastName: 'Morozov 15',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email15@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
    lastUpdate: new Date(2000, 2, 10, 1),
  },
  {
    id: 16,
    userName: 'Maxim 16',
    password: '111',
    repeatPassword: '111',
    userSRCAvatarIMG: [AvatarIMG7],
    firstName: 'Maxim',
    lastName: 'Morozov 16',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email16@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
    lastUpdate: new Date(2018, 2, 10, 1),
  },
  {
    id: 17,
    userName: 'Maxim 17',
    password: '2222',
    repeatPassword: '2222',
    userSRCAvatarIMG: [AvatarIMG1],
    firstName: 'Maxim',
    lastName: 'Morozov 17',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email17@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: 'Sport,fitness, aerobica and staff like that',
    checkboxJustWant: 'just want to play games, I’m not living in this life',
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxWtf: 'WTF is “hobbies”???',
    lastUpdate: new Date(2019, 4, 5, 1),
  },
  {
    id: 18,
    userName: 'Maxim 18',
    password: '2222',
    repeatPassword: '2222',
    userSRCAvatarIMG: [AvatarIMG2],
    firstName: 'Maxim',
    lastName: 'Morozov 18',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email18@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
    lastUpdate: new Date(2019, 4, 5, 1),
  },
  {
    id: 19,
    userName: 'Maxim 19',
    password: '111',
    repeatPassword: '111',
    userSRCAvatarIMG: [AvatarIMG3],
    firstName: 'Maxim',
    lastName: 'Morozov 19',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email19@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
    lastUpdate: new Date(2019, 4, 5, 1),
  },
  {
    id: 20,
    userName: 'Maxim 20',
    password: '111',
    repeatPassword: '111',
    userSRCAvatarIMG: [AvatarIMG4],
    firstName: 'Maxim',
    lastName: 'Morozov 20',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email20@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
    lastUpdate: new Date(2019, 4, 5, 1),
  },
  {
    id: 21,
    userName: 'Maxim 21',
    password: '111',
    repeatPassword: '111',
    userSRCAvatarIMG: [AvatarIMG5],
    firstName: 'Maxim',
    lastName: 'Morozov 21',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email21@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
    lastUpdate: new Date(2019, 4, 5, 1),
  },
  {
    id: 22,
    userName: 'Maxim 22',
    password: '111',
    repeatPassword: '111',
    userSRCAvatarIMG: [AvatarIMG6],
    firstName: 'Maxim',
    lastName: 'Morozov 22',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email22@gmail.com',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
    lastUpdate: new Date(2019, 4, 5, 1),
  },
  {
    id: 23,
    userName: 'Maxim 23',
    password: '111',
    repeatPassword: '111',
    userSRCAvatarIMG: [AvatarIMG7],
    firstName: 'Maxim',
    lastName: 'Morozov 23',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email23@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
    lastUpdate: new Date(2019, 4, 5, 1),
  },
  {
    id: 24,
    userName: 'Maxim 24',
    password: '111',
    repeatPassword: '111',
    userSRCAvatarIMG: [AvatarIMG7],
    firstName: 'Maxim',
    lastName: 'Morozov 24',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email24@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
    lastUpdate: new Date(2019, 4, 5, 1),
  },
  {
    id: 25,
    userName: 'Maxim 25',
    password: '2222',
    repeatPassword: '2222',
    userSRCAvatarIMG: [AvatarIMG1],
    firstName: 'Maxim',
    lastName: 'Morozov 25',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email25@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: 'Sport,fitness, aerobica and staff like that',
    checkboxJustWant: 'just want to play games, I’m not living in this life',
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxWtf: 'WTF is “hobbies”???',
    lastUpdate: new Date(2019, 4, 5, 1),
  },
  {
    id: 26,
    userName: 'Maxim 26',
    password: '2222',
    repeatPassword: '2222',
    userSRCAvatarIMG: [AvatarIMG2],
    firstName: 'Maxim',
    lastName: 'Morozov 26',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email26@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
    lastUpdate: new Date(2019, 4, 5, 1),
  },
  {
    id: 27,
    userName: 'Maxim 27',
    password: '111',
    repeatPassword: '111',
    userSRCAvatarIMG: [AvatarIMG3],
    firstName: 'Maxim',
    lastName: 'Morozov 27',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email27@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
    lastUpdate: new Date(2019, 4, 5, 1),
  },
  {
    id: 28,
    userName: 'Maxim 28',
    password: '111',
    repeatPassword: '111',
    userSRCAvatarIMG: [AvatarIMG4],
    firstName: 'Maxim',
    lastName: 'Morozov 28',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email28@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
    lastUpdate: new Date(2019, 4, 5, 1),
  },
  {
    id: 29,
    userName: 'Maxim 29',
    password: '111',
    repeatPassword: '111',
    userSRCAvatarIMG: [AvatarIMG5],
    firstName: 'Maxim',
    lastName: 'Morozov 29',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email29@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
    lastUpdate: new Date(2019, 4, 5, 1),
  },
  {
    id: 30,
    userName: 'Maxim 30',
    password: '111',
    repeatPassword: '111',
    userSRCAvatarIMG: [AvatarIMG6],
    firstName: 'Maxim',
    lastName: 'Morozov 30',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email30@gmail.com',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
    lastUpdate: new Date(2019, 4, 5, 1),
  },
  {
    id: 31,
    userName: 'Maxim 31',
    password: '111',
    repeatPassword: '111',
    userSRCAvatarIMG: [AvatarIMG7],
    firstName: 'Maxim',
    lastName: 'Morozov 31',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email31@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
    lastUpdate: new Date(2019, 4, 5, 1),
  },
  {
    id: 32,
    userName: 'Maxim 32',
    password: '111',
    repeatPassword: '111',
    userSRCAvatarIMG: [AvatarIMG7],
    firstName: 'Maxim',
    lastName: 'Morozov 32',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email32@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
    lastUpdate: new Date(2019, 4, 5, 1),
  },
  {
    id: 33,
    userName: 'Maxim 33',
    password: '2222',
    repeatPassword: '2222',
    userSRCAvatarIMG: [AvatarIMG1],
    firstName: 'Maxim',
    lastName: 'Morozov 33',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email33@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: 'Sport,fitness, aerobica and staff like that',
    checkboxJustWant: 'just want to play games, I’m not living in this life',
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxWtf: 'WTF is “hobbies”???',
    lastUpdate: new Date(2019, 4, 5, 1),
  },
  {
    id: 34,
    userName: 'Maxim 34',
    password: '2222',
    repeatPassword: '2222',
    userSRCAvatarIMG: [AvatarIMG2],
    firstName: 'Maxim',
    lastName: 'Morozov 34',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email34@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
    lastUpdate: new Date(2019, 4, 5, 1),
  },
  {
    id: 35,
    userName: 'Maxim 35',
    password: '111',
    repeatPassword: '111',
    userSRCAvatarIMG: [AvatarIMG3],
    firstName: 'Maxim',
    lastName: 'Morozov 35',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email35@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
    lastUpdate: new Date(2019, 4, 5, 1),
  },
  {
    id: 36,
    userName: 'Maxim 36',
    password: '111',
    repeatPassword: '111',
    userSRCAvatarIMG: [AvatarIMG4],
    firstName: 'Maxim',
    lastName: 'Morozov 36',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email36@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
    lastUpdate: new Date(2019, 4, 5, 1),
  },
  {
    id: 37,
    userName: 'Maxim 37',
    password: '111',
    repeatPassword: '111',
    userSRCAvatarIMG: [AvatarIMG5],
    firstName: 'Maxim',
    lastName: 'Morozov 37',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email37@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
    lastUpdate: new Date(2019, 4, 5, 1),
  },
  {
    id: 38,
    userName: 'Maxim 38',
    password: '111',
    repeatPassword: '111',
    userSRCAvatarIMG: [AvatarIMG6],
    firstName: 'Maxim',
    lastName: 'Morozov 38',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email38@gmail.com',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
    lastUpdate: new Date(2019, 4, 5, 1),
  },
  {
    id: 39,
    userName: 'Maxim 39',
    password: '111',
    repeatPassword: '111',
    userSRCAvatarIMG: [AvatarIMG7],
    firstName: 'Maxim',
    lastName: 'Morozov 39',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email39@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
    lastUpdate: new Date(2019, 4, 5, 1),
  },
  {
    id: 40,
    userName: 'Maxim 40',
    password: '111',
    repeatPassword: '111',
    userSRCAvatarIMG: [AvatarIMG7],
    firstName: 'Maxim',
    lastName: 'Morozov 40',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email40@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
    lastUpdate: new Date(2019, 4, 5, 1),
  },
]
