import AvatarIMG1 from '../img/Ellipse(1).png'
import AvatarIMG2 from '../img/Ellipse(2).png'
import AvatarIMG3 from '../img/Ellipse(3).png'
import AvatarIMG4 from '../img/Ellipse(4).png'
import AvatarIMG5 from '../img/Ellipse(5).png'
import AvatarIMG6 from '../img/Ellipse(6).png'
import AvatarIMG7 from '../img/Ellipse(7).png'


export const users = [
  {
    id: 1,
    userName: 'Maxim Morozov 1',
    password: '2222',
    repeatPassword: '2222',
    userSRCAvatarIMG: [AvatarIMG1],
    firstName: 'Maxim',
    lastName: 'Morozov',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email1@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: 'Sport,fitness, aerobica and staff like that',
    checkboxJustWant: 'just want to play games, I’m not living in this life',
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxWtf: 'WTF is “hobbies”???',
  },
  {
    id: 2,
    userName: 'Maxim Morozov 2',
    password: '2222',
    repeatPassword: '2222',
    userSRCAvatarIMG: [AvatarIMG2],
    firstName: 'Maxim',
    lastName: 'Morozov',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email2@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
  },
  {
    id: 3,
    userName: 'Maxim Morozov 3',
    password: '111',
    repeatPassword: '111',
    userSRCAvatarIMG: [AvatarIMG3],
    firstName: 'Maxim',
    lastName: 'Morozov',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email3@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
  },
  {
    id: 4,
    userName: 'Maxim Morozov 4',
    password: '111',
    repeatPassword: '111',
    userSRCAvatarIMG: [AvatarIMG4],
    firstName: 'Maxim',
    lastName: 'Morozov',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email4@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
  },
  {
    id: 5,
    userName: 'Maxim Morozov 5',
    password: '111',
    repeatPassword: '111',
    userSRCAvatarIMG: [AvatarIMG5],
    firstName: 'Maxim',
    lastName: 'Morozov',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email5@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
  },
  {
    id: 6,
    userName: 'Maxim Morozov 6',
    password: '111',
    repeatPassword: '111',
    userSRCAvatarIMG: [AvatarIMG6],
    firstName: 'Maxim',
    lastName: 'Morozov',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email6@gmail.com',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
  },
  {
    id: 7,
    userName: 'Maxim Morozov 7',
    password: '111',
    repeatPassword: '111',
    userSRCAvatarIMG: [AvatarIMG7],
    firstName: 'Maxim',
    lastName: 'Morozov',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email7@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
  },
  {
    id: 8,
    userName: 'Maxim Morozov 8',
    password: '111',
    repeatPassword: '111',
    userSRCAvatarIMG: [AvatarIMG7],
    firstName: 'Maxim',
    lastName: 'Morozov',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email8@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
  },
  {
    id: 9,
    userName: 'Maxim Morozov 9',
    password: '2222',
    repeatPassword: '2222',
    userSRCAvatarIMG: [AvatarIMG1],
    firstName: 'Maxim',
    lastName: 'Morozov',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email9@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: 'Sport,fitness, aerobica and staff like that',
    checkboxJustWant: 'just want to play games, I’m not living in this life',
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxWtf: 'WTF is “hobbies”???',
  },
  {
    id: 10,
    userName: 'Maxim Morozov 10',
    password: '2222',
    repeatPassword: '2222',
    userSRCAvatarIMG: [AvatarIMG2],
    firstName: 'Maxim',
    lastName: 'Morozov',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email10@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
  },
  {
    id: 11,
    userName: 'Maxim Morozov 11',
    password: '111',
    repeatPassword: '111',
    userSRCAvatarIMG: [AvatarIMG3],
    firstName: 'Maxim',
    lastName: 'Morozov',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email11@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
  },
  {
    id: 12,
    userName: 'Maxim Morozov 12',
    password: '111',
    repeatPassword: '111',
    userSRCAvatarIMG: [AvatarIMG4],
    firstName: 'Maxim',
    lastName: 'Morozov',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email12@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
  },
  {
    id: 13,
    userName: 'Maxim Morozov 13',
    password: '111',
    repeatPassword: '111',
    userSRCAvatarIMG: [AvatarIMG5],
    firstName: 'Maxim',
    lastName: 'Morozov',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email13@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
  },
  {
    id: 14,
    userName: 'Maxim Morozov 14',
    password: '111',
    repeatPassword: '111',
    userSRCAvatarIMG: [AvatarIMG6],
    firstName: 'Maxim',
    lastName: 'Morozov',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email14@gmail.com',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
  },
  {
    id: 15,
    userName: 'Maxim Morozov 15',
    password: '111',
    repeatPassword: '111',
    userSRCAvatarIMG: [AvatarIMG7],
    firstName: 'Maxim',
    lastName: 'Morozov',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email15@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
  },
  {
    id: 16,
    userName: 'Maxim Morozov 16',
    password: '111',
    repeatPassword: '111',
    userSRCAvatarIMG: [AvatarIMG7],
    firstName: 'Maxim',
    lastName: 'Morozov',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email16@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
  },
  {
    id: 17,
    userName: 'Maxim Morozov 17',
    password: '2222',
    repeatPassword: '2222',
    userSRCAvatarIMG: [AvatarIMG1],
    firstName: 'Maxim',
    lastName: 'Morozov',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email17@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: 'Sport,fitness, aerobica and staff like that',
    checkboxJustWant: 'just want to play games, I’m not living in this life',
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxWtf: 'WTF is “hobbies”???',
  },
  {
    id: 18,
    userName: 'Maxim Morozov 18',
    password: '2222',
    repeatPassword: '2222',
    userSRCAvatarIMG: [AvatarIMG2],
    firstName: 'Maxim',
    lastName: 'Morozov',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email18@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
  },
  {
    id: 19,
    userName: 'Maxim Morozov 19',
    password: '111',
    repeatPassword: '111',
    userSRCAvatarIMG: [AvatarIMG3],
    firstName: 'Maxim',
    lastName: 'Morozov',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email19@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
  },
  {
    id: 20,
    userName: 'Maxim Morozov 20',
    password: '111',
    repeatPassword: '111',
    userSRCAvatarIMG: [AvatarIMG4],
    firstName: 'Maxim',
    lastName: 'Morozov',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email20@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
  },
  {
    id: 21,
    userName: 'Maxim Morozov 21',
    password: '111',
    repeatPassword: '111',
    userSRCAvatarIMG: [AvatarIMG5],
    firstName: 'Maxim',
    lastName: 'Morozov',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email21@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
  },
  {
    id: 22,
    userName: 'Maxim Morozov 22',
    password: '111',
    repeatPassword: '111',
    userSRCAvatarIMG: [AvatarIMG6],
    firstName: 'Maxim',
    lastName: 'Morozov',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email22@gmail.com',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
  },
  {
    id: 23,
    userName: 'Maxim Morozov 23',
    password: '111',
    repeatPassword: '111',
    userSRCAvatarIMG: [AvatarIMG7],
    firstName: 'Maxim',
    lastName: 'Morozov',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email23@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
  },
  {
    id: 24,
    userName: 'Maxim Morozov 24',
    password: '111',
    repeatPassword: '111',
    userSRCAvatarIMG: [AvatarIMG7],
    firstName: 'Maxim',
    lastName: 'Morozov',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email24@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
  },
  {
    id: 25,
    userName: 'Maxim Morozov 25',
    password: '2222',
    repeatPassword: '2222',
    userSRCAvatarIMG: [AvatarIMG1],
    firstName: 'Maxim',
    lastName: 'Morozov',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email25@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: 'Sport,fitness, aerobica and staff like that',
    checkboxJustWant: 'just want to play games, I’m not living in this life',
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxWtf: 'WTF is “hobbies”???',
  },
  {
    id: 26,
    userName: 'Maxim Morozov 26',
    password: '2222',
    repeatPassword: '2222',
    userSRCAvatarIMG: [AvatarIMG2],
    firstName: 'Maxim',
    lastName: 'Morozov',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email26@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
  },
  {
    id: 27,
    userName: 'Maxim Morozov 27',
    password: '111',
    repeatPassword: '111',
    userSRCAvatarIMG: [AvatarIMG3],
    firstName: 'Maxim',
    lastName: 'Morozov',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email27@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
  },
  {
    id: 28,
    userName: 'Maxim Morozov 28',
    password: '111',
    repeatPassword: '111',
    userSRCAvatarIMG: [AvatarIMG4],
    firstName: 'Maxim',
    lastName: 'Morozov',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email28@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
  },
  {
    id: 29,
    userName: 'Maxim Morozov 29',
    password: '111',
    repeatPassword: '111',
    userSRCAvatarIMG: [AvatarIMG5],
    firstName: 'Maxim',
    lastName: 'Morozov',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email29@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
  },
  {
    id: 30,
    userName: 'Maxim Morozov 30',
    password: '111',
    repeatPassword: '111',
    userSRCAvatarIMG: [AvatarIMG6],
    firstName: 'Maxim',
    lastName: 'Morozov',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email30@gmail.com',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
  },
  {
    id: 31,
    userName: 'Maxim Morozov 31',
    password: '111',
    repeatPassword: '111',
    userSRCAvatarIMG: [AvatarIMG7],
    firstName: 'Maxim',
    lastName: 'Morozov',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email31@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
  },
  {
    id: 32,
    userName: 'Maxim Morozov 32',
    password: '111',
    repeatPassword: '111',
    userSRCAvatarIMG: [AvatarIMG7],
    firstName: 'Maxim',
    lastName: 'Morozov',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email32@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
  },
  {
    id: 33,
    userName: 'Maxim Morozov 33',
    password: '2222',
    repeatPassword: '2222',
    userSRCAvatarIMG: [AvatarIMG1],
    firstName: 'Maxim',
    lastName: 'Morozov',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email33@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: 'Sport,fitness, aerobica and staff like that',
    checkboxJustWant: 'just want to play games, I’m not living in this life',
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxWtf: 'WTF is “hobbies”???',
  },
  {
    id: 34,
    userName: 'Maxim Morozov 34',
    password: '2222',
    repeatPassword: '2222',
    userSRCAvatarIMG: [AvatarIMG2],
    firstName: 'Maxim',
    lastName: 'Morozov',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email34@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
  },
  {
    id: 35,
    userName: 'Maxim Morozov 35',
    password: '111',
    repeatPassword: '111',
    userSRCAvatarIMG: [AvatarIMG3],
    firstName: 'Maxim',
    lastName: 'Morozov',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email35@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
  },
  {
    id: 36,
    userName: 'Maxim Morozov 36',
    password: '111',
    repeatPassword: '111',
    userSRCAvatarIMG: [AvatarIMG4],
    firstName: 'Maxim',
    lastName: 'Morozov',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email36@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
  },
  {
    id: 37,
    userName: 'Maxim Morozov 37',
    password: '111',
    repeatPassword: '111',
    userSRCAvatarIMG: [AvatarIMG5],
    firstName: 'Maxim',
    lastName: 'Morozov',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email37@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
  },
  {
    id: 38,
    userName: 'Maxim Morozov 38',
    password: '111',
    repeatPassword: '111',
    userSRCAvatarIMG: [AvatarIMG6],
    firstName: 'Maxim',
    lastName: 'Morozov',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email38@gmail.com',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
  },
  {
    id: 39,
    userName: 'Maxim Morozov 39',
    password: '111',
    repeatPassword: '111',
    userSRCAvatarIMG: [AvatarIMG7],
    firstName: 'Maxim',
    lastName: 'Morozov',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email39@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
  },
  {
    id: 40,
    userName: 'Maxim Morozov 40',
    password: '111',
    repeatPassword: '111',
    userSRCAvatarIMG: [AvatarIMG7],
    firstName: 'Maxim',
    lastName: 'Morozov',
    birthDate: new Date(2000, 2, 1),
    email: 'my_email40@gmail.com',
    address: 'Street TRUE, 130',
    gender: '',

    company: 'Company name',
    githubLink: '',
    facebookLink: 'facebook.com/',
    selectLanguage: null,
    fax: '+38 (066) 123 123 11',
    phoneArray: ['', '', ''],
    phoneN1: '+38 (066) 123 123 11',
    phoneN2: '+38 (066) 123 123 11',
    phoneN3: '+38 (066) 123 123 11',

    selectSkills: [{ value: 'CSS', label: 'CSS' },
      { value: 'Javascript', label: 'Javascript' },
      { value: 'jQuery', label: 'jQuery' },
      { value: 'React', label: 'React' }],
    textareaField: 'Guitar, guitar and guitar again. I’m fall in love with it.',
    checkboxArt: 'Art',
    checkboxSport: false,
    checkboxJustWant: false,
    checkboxFemale: 'I’m a female... I’m doing nothing. Every day.',
    checkboxGuitar: false,
    checkboxWtf: false,
  },
]
